name: Publish to Docker
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: fjorgemota
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: fjorgemota/gha-mjolnir
          tag_with_sha: true